services:
  - type: web
    name: aldeia-site-oficial
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: SESSION_SIGNING_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD_HASH
        sync: false
